apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}"
  namespace: "{{ .Values.app.env }}"
  labels:
    app: "{{ .Values.app.name }}"
spec:
  replicas: "{{ .Values.app.replicas }}"
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}"
    spec:
      containers:
        - name: credit-card-mgmt
          image: "{{ .Values.app.image.name }}:{{ .Values.app.image.version }}"
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: http