apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-service"
  namespace: "{{ .Values.app.env }}"
  labels:
    app: "{{ .Values.app.name }}"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: {{ .Values.app.port }}
  selector:
    app: "{{ .Values.app.name }}"