name: Build CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/helm/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'    
      - '**/helm/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_PASSWORD }}         
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.HUB_USERNAME }}/creditcardmgmt:$(git rev-parse --short HEAD)
    - name: Push the Docker image to Docker Hub
      run: docker push ${{ secrets.HUB_USERNAME }}/creditcardmgmt:$(git rev-parse --short HEAD)
